### ISSUE TITLE
Incorrect Vector class API

### ISSUE THREAD

**Issue by nogov** [Transportnick/MTP_Lab2#1]
Vector operations should not return `int[]`. Prefer using more object-oriented abstractions to primitives.

**Comment by nogov** [comment]
Vector class should also have `X` and `Y` properties.
```csharp
public int X {get; private set;}
public int Y {get; private set;}
```
And a corresponding constructor with parameters `x` and `y` to initialize those properties.

**Comment by DarkWindman** [comment]
> Vector class should also have `X` and `Y` properties.
> 
> `public int X {get; private set;}`
> `public int Y {get; private set;}`
> 
> And a corresponding constructor with parameters `x` and `y` to initialize those properties.

I don't really understand what you mean by the fact that I shouldn't return an array. Do I need to write an array to an object? And return it? Or everything is much simpler and I need to write for example:
public int x, y;
         public Vector (int x, int y)
         {
             this.x = x;
             this.y = y;
         }

         public int [] addition ()
         {
             int [] v = new int [2] {x + x, y + y};
             return v;
         }

**Comment by nogov** [comment]
Yes, correct.

However, instead of returning `int[]` you can return a new instance of resulting Vector.
So, simply
```csharp
public Vector Addition(Vector a, Vector b)
{
  return new Vector(a.x + b.x, a.y + b.y);
}
```

**Comment by nogov** [comment]
I would also recommend to overload operators so the usage is more convenient:
```csharp
public static Vector operator +(Vector a, Vector b)
{
  return new Vector(a.x + b.x, a.y + b.y);
}
```
Then you can add vectors as any other numeric primitive types.

**Comment by DarkWindman** [comment]
> Yes, correct.



> I would also recommend to overload operators so the usage is more convenient:

Thank you so much. It seems to have worked out. Also used operator overloading as you suggested. Could you check?

**Comment by nogov** [comment]
All good, except that x, y, z can be modified outside of the class - encapsulation violation. You could use properties with private setters instead.

**Comment by DarkWindman** [comment]
> except that x, y, z can be modified outside of the class - encapsulation violation. You could use properties with private setters instead.

Okay, as I understand I need to do my x,y,z like:

public int x { private set; get; }
public int y { private set; get; }
public int z { private set; get; }

We can`t modifed outside of the class(private set), but can read them(get).
